In [15]:
import os
import numpy as np
from scipy.misc import imread, imresize, imsave
from skimage.color import rgb2luv

In [43]:
from matplotlib import pyplot as plt
from keras.utils import to_categorical

Using TensorFlow backend.


In [12]:
for root,dirs,files in os.walk('Opencountry'):
    for file in files:
        print(str(file))
        img = imresize(imread("Opencountry/"+file, mode='RGB'), (224, 224)).astype(np.float32)
        imsave("Resized/"+file,img)

art582.jpg
cdmc109.jpg
cdmc276.jpg
cdmc354.jpg
cdmc518.jpg
cdmc710.jpg
cdmc712.jpg
cdmc713.jpg
cdmc722.jpg
cdmc753.jpg
cdmc795.jpg
cdmc935.jpg
cdmc937.jpg
des16.jpg
fie10.jpg
fie12.jpg
fie13.jpg
fie14.jpg
fie15.jpg
fie21.jpg
fie23.jpg
fie24.jpg
fie25.jpg
fie26.jpg
fie27.jpg
fie28.jpg
fie30.jpg
fie33.jpg
fie35.jpg
fie36.jpg
fie37.jpg
fie43.jpg
fie46.jpg
fie48.jpg
fie5.jpg
fie50.jpg
fie6.jpg
fie7.jpg
for68.jpg
land147.jpg
land194.jpg
land202.jpg
land206.jpg
land218.jpg
land220.jpg
land228.jpg
land233.jpg
land238.jpg
land239.jpg
land269.jpg
land271.jpg
land276.jpg
land285.jpg
land290.jpg
land291.jpg
land295.jpg
land297.jpg
land299.jpg
land342.jpg
land345.jpg
land348.jpg
land350.jpg
land351.jpg
land352.jpg
land353.jpg
land355.jpg
land358.jpg
land359.jpg
land364.jpg
land381.jpg
land388.jpg
land406.jpg
land41.jpg
land412.jpg
land416.jpg
land42.jpg
land433.jpg
land443.jpg
land472.jpg
land48.jpg
land493.jpg
land494.jpg
land500.jpg
land501.jpg
land505.jpg
land507.jpg
land51.jpg
land513.jpg
land

In [13]:
print(len(files))

410


In [23]:
input_images = []
target_values = []
MEAN_VALUES = np.array([104, 117, 123]).reshape((1,1,3))
print(MEAN_VALUES)
for root,dirs,files in os.walk('Resized'):
    for file in files:
        rgb = imread("Resized/"+file, mode='RGB')
        luv = rgb2luv(rgb)
        grayscale = luv[:,:,0]
        target = luv[:,:,1:]
        
        grayscale = np.array(grayscale)
        input_image = np.repeat(grayscale[:, :, np.newaxis],3,axis=2)
        input_image = input_image - MEAN_VALUES
        #print(input_image[:,:,0])
        #print(input_image[:,:,1])
        #print(input_image[:,:,2])
        input_images.append(input_image)
        target_values.append(target)

[[[104 117 123]]]


In [26]:
np.save('input_images.npy',input_images)

In [33]:
np.unique(target_values[6])

array([-50.22603445, -50.03834502, -49.97413706, ...,  51.29880915,
        52.4115936 ,  52.53214685])

In [51]:
target_values[0].shape

(224, 224, 2)

In [52]:
bins = np.linspace(-100,100,num=50)

In [53]:
bins

array([-100.        ,  -95.91836735,  -91.83673469,  -87.75510204,
        -83.67346939,  -79.59183673,  -75.51020408,  -71.42857143,
        -67.34693878,  -63.26530612,  -59.18367347,  -55.10204082,
        -51.02040816,  -46.93877551,  -42.85714286,  -38.7755102 ,
        -34.69387755,  -30.6122449 ,  -26.53061224,  -22.44897959,
        -18.36734694,  -14.28571429,  -10.20408163,   -6.12244898,
         -2.04081633,    2.04081633,    6.12244898,   10.20408163,
         14.28571429,   18.36734694,   22.44897959,   26.53061224,
         30.6122449 ,   34.69387755,   38.7755102 ,   42.85714286,
         46.93877551,   51.02040816,   55.10204082,   59.18367347,
         63.26530612,   67.34693878,   71.42857143,   75.51020408,
         79.59183673,   83.67346939,   87.75510204,   91.83673469,
         95.91836735,  100.        ])

In [54]:
u_channel_targets = []
v_channel_targets = []
for target in target_values:
    target = np.array(target)
    quantized_target = np.digitize(target,bins)
    #print(quantized_target)
    #print(np.unique(quantized_target))
    
    u_channel = quantized_target[:,:,0]
    v_channel = quantized_target[:,:,1]
    #print(v_channel.shape)
    
    u_categorical = to_categorical(u_channel, num_classes = 50)
    v_categorical = to_categorical(v_channel, num_classes=50)
    #print(u_categorical.shape)
    #print(u_categorical)
    u_channel_targets.append(u_categorical)
    v_channel_targets.append(v_categorical)

IndexError: index 50 is out of bounds for axis 1 with size 50

In [41]:
np.save('quantized_targets.npy',quantized_targets)

In [42]:
quantized_targets[0].shape

(224, 224, 2)